      # 3. تحميل المكتبات المطلوبة
      - name: Install Dependencies
        run: flutter pub get

      # الخطوة الجديدة: توجيه السيرفر لإنشاء ملفات الأندرويد الناقصة
      - name: Generate Android Files
        run: flutter create .

      # 4. تجميع التطبيق وإنتاج ملف APK الأصلي
      - name: Build APK
        run: flutter build apk --release

